[package]
name = "neon-frame-macro"
version = "0.1.0-dev"
edition = "2021"
authors = ["Emerald Team", "Igor Artamonov"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", feautures= ["full", "derive", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
